# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G2YUh2En3Tl-hMFQugOEmfH4fiegnf0c
"""

contador = 0
while (contador < 6):
   print("Regue a planta" , contador , "tomate")
   contador = contador + 2

## André Moura, Claudemir Oliveira, José Carlos Domingos.
