# -*- coding: utf-8 -*-
"""Cópia de Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1is-iIFT36TULivFZdiHdIOTWmLABZusR
"""

contador = 0
while (contador < 5):
   print("Regue a planta" , contador)
   contador = contador + 1