# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRBKGpSET4ktg51LqB2pgbXjNM0WGps3
"""

numero1 = input("Digite o primeiro número: ")
numero2 = input("Digite o segundo número: ")

operacao = input("Digite a operacao desejada (soma, sub, mult, div): ")
if operacao == "soma":
	resultado = int(numero1) + int(numero2)
elif operacao == "sub":
	resultado = int(numero1) - int(numero2)
elif operacao == "mult":
	resultado = int(numero1) * int(numero2)
elif operacao == "div":
	resultado = int(numero1) / int(numero2)
elif operacao:
	resultado = 0
    

print(resultado)